language: php

php:
  - '7.0'
  - '7.1'

services:
  - redis-server

before_install: v=$(phpenv version-name); if [ ${v:0:1} -lt 7 ]; then pecl install igbinary ; yes | pecl install redis; else echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

install:
  - composer global require --prefer-dist "fxp/composer-asset-plugin:^1.2.0"
  - composer require codeclimate/php-test-reporter --dev --prefer-dist
  - composer install --no-progress --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

addons:
  code_climate:
    repo_token: 255db28eb13c47dff54362135d879145fc97afff3eb91d97158608818bb4d1a9

after_script:
  - vendor/bin/test-reporter
